<?php
/**
 * @var Cronical\Api\Representation\ScheduledActionRepresentation[] $scheduledActions
 */

$this->htmlElement('body')->appendAttribute('class', 'browse cronical cronical-scheduled-action-runs');
$userIsAllowedBatchDelete = $this->userIsAllowed('Cronical\Api\Adapter\ScheduledActionAdapter', 'batch_delete');
?>

<?= $this->pageTitle($this->translate('Scheduled action runs')) ?>

<?= $this->cronicalScheduledActionRunSearchFilters() ?>

<div class="browse-controls">
    <?= $this->pagination() ?>
    <?= $this->hyperlink($this->translate('Advanced search'), $this->url('admin/cronical/default', ['controller' => 'scheduled-action-run', 'action' => 'search'], ['query' => $this->params()->fromQuery()]), ['class' => 'advanced-search']); ?>
    <?= $this->browse()->renderSortSelector('cronical_scheduled_action_runs') ?>
</div>

<?php $this->trigger('view.browse.before'); ?>

<?php if (count($scheduledActionRuns)): ?>
    <form method="post" id="batch-form" class="disable-unsaved-warning">
        <?php if ($userIsAllowedBatchDelete): ?>
            <div class="batch-inputs">
                <select class="batch-actions-select" name="batch_action" aria-label="<?= $this->escapeHtml($this->translate('Batch actions')) ?>">
                    <option value="default"><?= $this->escapeHtml($this->translate('Batch actions')) ?></option>

                    <?php if ($userIsAllowedBatchDelete): ?>
                        <option value="delete-selected" class="batch-selected" disabled><?= $this->escapeHtml($this->translate('Delete selected')) ?></option>
                        <option value="delete-all"><?= $this->escapeHtml($this->translate('Delete all')) ?></option>
                    <?php endif; ?>
                </select>

                <div class="batch-actions">
                    <button type="button" class="default active" disabled><?= $this->escapeHtml($this->translate('Go')) ?></button>

                    <input type="hidden" name="query" class="batch-query" value="<?= $this->escapeHtml(json_encode($this->params()->fromQuery())) ?>">

                    <?php if ($userIsAllowedBatchDelete): ?>
                        <a class="delete button sidebar-content delete-selected" data-sidebar-selector="#sidebar-delete-selected"><?= $this->escapeHtml($this->translate('Go')) ?></a>
                        <a class="delete button sidebar-content delete-all" data-sidebar-selector="#sidebar-delete-all"><?= $this->escapeHtml($this->translate('Go')) ?></a>
                    <?php endif; ?>
                </div>
            </div>
        <?php endif; ?>

        <table class="tablesaw batch-edit" data-tablesaw-mode="stack">
            <thead>
                <tr>
                    <th>
                        <input type="checkbox" class="select-all">
                        <?= $this->escapeHtml($this->translate('ID')) ?>
                    </th>
                    <th><?= $this->escapeHtml($this->translate('Scheduled action')) ?></th>
                    <th><?= $this->escapeHtml($this->translate('Started')) ?></th>
                    <th><?= $this->escapeHtml($this->translate('Ended')) ?></th>
                    <th><?= $this->escapeHtml($this->translate('Status')) ?></th>
                    <th><?= $this->escapeHtml($this->translate('Job')) ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($scheduledActionRuns as $scheduledActionRun): ?>
                    <?php $userIsAllowedDelete = $scheduledActionRun->userIsAllowed('delete'); ?>
                    <?php $scheduledAction = $scheduledActionRun->scheduledAction(); ?>
                    <?php $action = $this->cronical()->getAction($scheduledAction->action()); ?>
                    <tr>
                        <td>
                            <?php if ($userIsAllowedBatchDelete): ?>
                                <input type="checkbox" name="resource_ids[]" value="<?= $scheduledActionRun->id() ?>"<?php if (!($userIsAllowedDelete)): ?> disabled="disabled"<?php endif; ?>>
                            <?php endif; ?>

                            <span>
                                <?= $scheduledActionRun->link($scheduledActionRun->id()) ?>
                            </span>

                            <ul class="actions">
                                <?php $this->trigger('view.browse.actions', ['resource' => $scheduledActionRun]); ?>

                                <?php if ($userIsAllowedDelete): ?>
                                    <li><?= $this->hyperlink('', '#', [
                                        'data-sidebar-content-url' => $scheduledActionRun->url('delete-confirm'),
                                        'class' => 'o-icon-delete sidebar-content',
                                        'title' => $this->translate('Delete'),
                                        'data-sidebar-selector' => '#sidebar-delete-selected',
                                    ]) ?></li>
                                <?php endif; ?>

                                <li><?= $this->hyperlink('', '#', [
                                    'data-sidebar-content-url' => $scheduledActionRun->url('show-details'),
                                    'class' => 'o-icon-more sidebar-content',
                                    'title' => $this->translate('Details'),
                                    'data-sidebar-selector' => '#sidebar',
                                ]) ?></li>
                            </ul>
                        </td>
                        <td><?= $scheduledAction->link($scheduledAction->name()) ?></td>
                        <td><?= $this->i18n()->dateFormat($scheduledActionRun->started(), 'full', 'short') ?></td>
                        <td><?= $this->i18n()->dateFormat($scheduledActionRun->ended(), 'full', 'short') ?></td>
                        <td><?= $this->escapeHtml($this->translate($scheduledActionRun->statusLabel())) ?></td>
                        <td>
                            <?php if ($job = $scheduledActionRun->job()): ?>
                                <?= $job->link(sprintf('#%d (%s)', $job->id(), $this->translate($job->statusLabel()))) ?>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </form>

    <?php $this->trigger('view.browse.after'); ?>

    <div class="browse-controls">
        <?= $this->pagination() ?>
    </div>

    <div id="sidebar" class="sidebar">
        <?= $this->hyperlink('', '#', [
            'class' => 'sidebar-close o-icon-close',
            'title' => $this->translate('Close'),
        ]) ?>

        <div class="sidebar-content"></div>
    </div>

    <?php if ($userIsAllowedBatchDelete): ?>
        <div id="sidebar-delete-selected" class="sidebar">
            <?= $this->hyperlink('', '#', [
                'class' => 'sidebar-close o-icon-close',
                'title' => $this->translate('Close'),
            ]) ?>
            <div class="sidebar-content">
                <div id="sidebar-confirm">
                    <h3><?= $this->escapeHtml($this->translate('Delete scheduled action runs')) ?></h3>
                    <p><?= $this->escapeHtml($this->translate('Are you sure you would like to delete the selected scheduled action runs?')) ?></p>
                    <p class="error"><?= sprintf(
                        $this->escapeHtml($this->translate('%1$s: this action will permanently delete %2$s scheduled action runs and cannot be undone.')),
                        sprintf('<strong>%s</strong>', $this->escapeHtml($this->translate('Warning'))),
                        '<strong><span id="delete-selected-count"></span></strong>'
                    ); ?></p>
                    <?= $this->form($this->formDeleteSelected) ?>
                </div>
            </div>
        </div>

        <div id="sidebar-delete-all" class="sidebar">
            <?= $this->hyperlink('', '#', [
                'class' => 'sidebar-close o-icon-close',
                'title' => $this->translate('Close'),
            ]) ?>
            <div class="sidebar-content">
                <div id="sidebar-confirm">
                    <h3><?= $this->escapeHtml($this->translate('Delete scheduled action runs')) ?></h3>
                    <p><?= $this->escapeHtml($this->translate('Are you sure you would like to delete all scheduled action runs on all pages of this result?')) ?></p>
                    <p class="error"><?= sprintf(
                        $this->escapeHtml($this->translate('%1$s: this action will permanently delete %2$s scheduled action runs and cannot be undone.')),
                        sprintf('<strong>%s</strong>', $this->escapeHtml($this->translate('Warning'))),
                        sprintf('<strong>%s</strong>', number_format($this->pagination()->getPaginator()->getTotalCount()))
                    ); ?></p>
                    <label><input type="checkbox" name="confirm-delete-all-check"> <?= $this->escapeHtml($this->translate('Are you sure?')) ?></label>
                    <?= $this->form($this->formDeleteAll) ?>
                </div>
            </div>
        </div>

        <script>
        // Complete the batch delete form after confirmation.
        $('#confirm-delete-selected, #confirm-delete-all').on('submit', function(e) {
            var confirmForm = $(this);
            if ('confirm-delete-all' === this.id) {
                confirmForm.append($('.batch-query').clone());
            } else {
                $('#batch-form').find('input[name="resource_ids[]"]:checked:not(:disabled)').each(function() {
                    confirmForm.append($(this).clone().prop('disabled', false).attr('type', 'hidden'));
                });
            }
        });
        $('.delete-all').on('click', function(e) {
            Omeka.closeSidebar($('#sidebar-delete-selected'));
        });
        $('.delete-selected').on('click', function(e) {
            Omeka.closeSidebar($('#sidebar-delete-all'));
            var inputs = $('input[name="resource_ids[]"]');
            $('#delete-selected-count').text(inputs.filter(':checked').length);
        });
        $('#sidebar-delete-all').on('click', 'input[name="confirm-delete-all-check"]', function(e) {
            $('#confirm-delete-all input[type="submit"]').prop('disabled', this.checked ? false : true);
        });
        </script>
    <?php endif; ?>
<?php else: ?>
    <div class="no-resources">
        <p><?= $this->escapeHtml($this->translate('Omeka could not find any scheduled action runs.')) ?></p>
    </div>
<?php endif; ?>
